version: '3.5'
services:
  serve:
    build: .
    image: teeto_club
    container_name: teeto_club
    restart: always
    environment:
      - VIRTUAL_HOST=ttsslab.com
    networks:
      - utohub

networks:
  utohub:
    external: true